package com.test.ecommerce.output.entities;

// default package
// Generated Mar 23, 2016 4:48:05 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "CART", catalog = "Ankita")
public class Cart implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer orderId;
	private Customer customerId;
	private Product productId;
	private String quantityOrdered;
	private BigDecimal CProdPrice;
	private BigDecimal totalAmount;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ORDER_ID", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/*
	 * Added to Support One to One mapping based on CustomerId
	 */
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "CUSTOMER_ID", nullable = false)
	public Customer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Customer customerId) {
		this.customerId = customerId;
	}

	/*
	 * Added to Support One to One mapping based on ProductId
	 */
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public Product getProductId() {
		return productId;
	}

	public void setproductId(Product productId) {
		this.productId = productId;
	}

	@Column(name = "QUANTITY_ORDERED", nullable = false, length = 20)
	public String getQuantityOrdered() {
		return this.quantityOrdered;
	}

	public void setQuantityOrdered(String quantityOrdered) {
		this.quantityOrdered = quantityOrdered;
	}

	@Column(name = "C_PROD_PRICE", nullable = false, precision = 10)
	public BigDecimal getCProdPrice() {
		return this.CProdPrice;
	}

	public void setCProdPrice(BigDecimal CProdPrice) {
		this.CProdPrice = CProdPrice;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	// TODO need to check the use of orders variable otherwise remove
	/*
	 * Added to Support One to One mapping based on OrderID
	 */
	@OneToOne(mappedBy = "cart", cascade = CascadeType.ALL)
	private Orders orders;

	public Cart() {
	}

	/*
	 * Modified Constructors to support mapping
	 */
	public Cart(Customer customerId, Product productId, String quantityOrdered, BigDecimal CProdPrice,
			BigDecimal totalAmount) {
		this.customerId = customerId;
		this.productId = productId;
		this.quantityOrdered = quantityOrdered;
		this.CProdPrice = CProdPrice;
		this.totalAmount = totalAmount;
	}

}
