package com.test.ecommerce.output.entities;

// default package
// Generated Mar 23, 2016 4:48:05 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "CART", catalog = "Ankita")
public class Cart implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer orderId;
	private int customerId;
	private int productId;
	private String quantityOrdered;
	private BigDecimal CProdPrice;
	private BigDecimal totalAmount;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ORDER_ID", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "CUSTOMER_ID", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "PRODUCT_ID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "QUANTITY_ORDERED", nullable = false, length = 20)
	public String getQuantityOrdered() {
		return this.quantityOrdered;
	}

	public void setQuantityOrdered(String quantityOrdered) {
		this.quantityOrdered = quantityOrdered;
	}

	@Column(name = "C_PROD_PRICE", nullable = false, precision = 10)
	public BigDecimal getCProdPrice() {
		return this.CProdPrice;
	}

	public void setCProdPrice(BigDecimal CProdPrice) {
		this.CProdPrice = CProdPrice;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	// TODO
	// Needs to verify this one to one mapping
	@OneToOne(mappedBy = "cart", cascade = CascadeType.ALL)
	private Orders orders;

	public Cart() {
	}

	public Cart(int customerId, int productId, String quantityOrdered, BigDecimal CProdPrice, BigDecimal totalAmount) {
		this.customerId = customerId;
		this.productId = productId;
		this.quantityOrdered = quantityOrdered;
		this.CProdPrice = CProdPrice;
		this.totalAmount = totalAmount;
	}

}
