package com.test.ecommerce.output.entities;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated Mar 23, 2016 4:48:05 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity(name = "Item")
@Table(name = "PRODUCT", catalog = "Ankita")
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer productId;
	private String productName;
	private String manufacturer;
	private BigDecimal sellingPrice;
	private String stock;

	/*
	 * Many-to-One with Cart
	 */
	private Cart cart;

	public Product() {
	}

	public Product(String productName, BigDecimal sellingPrice, String stock) {
		this.productName = productName;
		this.sellingPrice = sellingPrice;
		this.stock = stock;
	}

	public Product(String productName, String manufacturer, BigDecimal sellingPrice, String stock) {
		this.productName = productName;
		this.manufacturer = manufacturer;
		this.sellingPrice = sellingPrice;
		this.stock = stock;
	}

	/*
	 * Annotation used and changes done to support Many to One mapping
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	//@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "PRODUCT_NAME", unique = true, nullable = false, length = 20)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "MANUFACTURER", length = 32)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "SELLING_PRICE", nullable = false, precision = 10)
	public BigDecimal getSellingPrice() {
		return this.sellingPrice;
	}

	public void setSellingPrice(BigDecimal sellingPrice) {
		this.sellingPrice = sellingPrice;
	}

	@Column(name = "STOCK", nullable = false, length = 20)
	public String getStock() {
		return this.stock;
	}

	public void setStock(String stock) {
		this.stock = stock;
	}

	/*
	 * Added to support Many-to-One with Cart
	 */
	@ManyToOne(cascade = CascadeType.ALL)
	public Cart getCart() {
		return cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

}
